#!/bin/sh
echo "Heroku: te veo por el visor de mi rifle - `date`"
USERID=$1 #ini 3
PUBLIID=$2  #ini 2
INIUSER=$USERID
INIRANGE=$PUBLIID
curl --silent -X POST "https://bookspace-app.herokuapp.com/api/users" -H "accept: */*" -H "Content-Type: application/json" -d "{ \"dob\": \"1976-05-02\", \"email\": \"ferrancarmona@hotmail.com\", \"favCategories\": [ \"comic\", \"fantasy\" ], \"name\": \"Ferran Carmona\", \"password\": \"hD&h2VTwhJ!w\", \"username\": \"f_carmona123\"}"
curl --silent -X PUT "https://bookspace-app.herokuapp.com/api/users/$USERID" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"description\": \"Este usuario prefiere mantener un aire de misterio sobre si mismo.\" }"
USERID=$((USERID + 1))
curl --silent -X POST "https://bookspace-app.herokuapp.com/api/users" -H "accept: */*" -H "Content-Type: application/json" -d "{ \"dob\": \"1960-01-01\", \"email\": \"nayaraarcos@hotmail.com\", \"favCategories\": [ \"adult\", \"economy\" ], \"name\": \"Nayara Arcos\", \"password\": \"1^JuVDi1$!6h\", \"username\": \"arcos99\"}"
curl --silent -X PUT "https://bookspace-app.herokuapp.com/api/users/$USERID" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"description\": \"Solo una humana en internet.\" }"
curl --silent -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"romantic\", \"content\": \"Hola! Sé que parecerá spam, pero no lo es. Quiero invitaros a que leais la especie de novela que estoy escribiendo y que me digáis lo que os parece, si os gusta o si no, y como cambiaríais la trama. Gracias! https://www.wattpad.com/665725432\", \"mentions\": [ \"\" ], \"tags\": [ \"romantica\", \"apasionante\" ], \"title\": \"ESTOY ESCRIBIENDO UNA NUEVA NOVELA\"}"
curl --silent -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"comic\", \"content\": \"Pues eso. Estoy decidido a hacerlo. Tengo la idea general y algunos personajes. Necesito ideas sobre alguna conspiración con alguna secta o algo relacionado con brujas. Prometo saludaros en el libro si logro publicarlo. Gracias de antebrazo.\", \"mentions\": [ \"\" ], \"tags\": [ \"brujas\" ], \"title\": \"Voy a escribir una novela.Ideas???\"}"
curl --silent -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"adult\", \"content\": \"Por favor tema serio, no trolleis porque el tema tampoco es que tenga mucha chicha para trollearlo.... Al lio. Quiero empezar a escribir un libro erotico, ya que tengo tiempo libre y siempre he querido escribir uno. Acudo a vosotros, los shurs que ya han escrito algun que otro, los que incluso han publicado en Amazon y demas paginas. Todo consejo que me deis sera muy bien aceptado. Mi intencion es escribir uno tipo 50 sombras de gray. Gracias por los consejos y por la ayuda.\", \"mentions\": [ \"\" ], \"tags\": [ \"erotico\" ], \"title\": \"Ayuda y consejos para empezar a escribir un relato [Tema Serio]\"}"
USERID=$((USERID + 1))
curl --silent -X POST "https://bookspace-app.herokuapp.com/api/users" -H "accept: */*" -H "Content-Type: application/json" -d "{ \"dob\": \"1999-06-01\", \"email\": \"moviedo@hotmail.com\", \"favCategories\": [ \"adult\", \"contemporary\", \"romantic\" ], \"name\": \"Modesto Oviedo\", \"password\": \"0ztuO5dTo%$u\", \"username\": \"m0v1edo\"}"
curl --silent -X PUT "https://bookspace-app.herokuapp.com/api/users/$USERID" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"description\": \"Una persona que disfruta construir mundos.\" }"
curl --silent -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"historic\", \"content\": \"Hola buenas soy nueva y tengo un problema. Me encanta la mitologia griega, nordica y cristiana pero me cuedta encontrar libros interesantes sobre todo de esta ultima. Me gusta todo lo que son conflictos entre dioses y vriaturas mitologicas pero para encontrar libros asi me supone un mundo. Me gustaria leer algo de la caida de lucifer y la guerra entre angeles y demonios, del mito del leviatan, del Ragnarok, de la titanomaquia, cualquier cosa asi. Espero que me podais ayudar y gracias de antemano.\", \"mentions\": [ \"\" ], \"tags\": [ \"mitologia\" ], \"title\": \"RECOMENDADME ALGO PLSS!!\"}"
curl --silent -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"crime\", \"content\": \"Necesito consejos de escritores del foro que puedan ayudarme.. La idea la tengo y escribir ya escribo bien pero seguro que un escritor experto me puede asesorar sobre escritura o técnicas que usan los escritores de crimenes\", \"mentions\": [ \"\" ], \"tags\": [ \"crimenes\" ], \"title\": \"Voy a escribir un libro de crimenes pido consejos a escritores también\"}"
curl --silent -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"historic\", \"content\": \"Entiendo que los pterosaurios y las aves evolucionaron de tener dientes a picos, ya que los picos son más ligeros que los dientes y pueden cumplir la misma función. los pterosaurios ponen huevos, y las aves actualmente ponen huevos, mientras que los murciélagos dan a luz a crías vivas. Además, hasta donde yo sé, no hay mamíferos placentarios que tengan picos. ¿Sería posible que los murciélagos desarrollaran picos como una adaptación al vuelo?. Es para un libro, thx.\", \"mentions\": [ \"\" ], \"tags\": [ \"fantasia\" ], \"title\": \"¿Podrían los murciélagos evolucionar para tener picos?\"}"
curl --silent -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"other\", \"content\": \"¿Cómo se puede demostrar que una especie tiene el potencial de volverse plenamente inteligente como nosotros, pero aún no lo ha logrado? Hasta ahora tengo estructura social y apéndices versátiles. Me gustaría publicar una teoria en mi siguente libro, gracias por su ayuda.\", \"mentions\": [ \"\" ], \"tags\": [ \"apasionante\" ], \"title\": \"Potencial sutil\"}"
curl --silent -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"fantasy\", \"content\": \"Quiero una familia de humanos que nazcan con instintos que provengan de sus padres. Padre herrero y madre cazadora de vampiros = niño atraído por la metalurgia y con un odio e instintos naturales para asesinar vampiros. ¿Qué se debe modificar en el ADN humano para que sea posible? ¿Lo agito con la mano con magia?.\", \"mentions\": [ \"\" ], \"tags\": [ \"fantasia\" ], \"title\": \"Personalidad genética\"}"
curl -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"economy\", \"content\": \"¿Alguien del foro tendría idea de como estructurar un libro sobre fondos de gestion activa?\", \"mentions\": [ \"\" ], \"tags\": [ \"fondos\" ], \"title\": \"Fondos de gestion activa, Ayuda\"}"
PUBLIID=$((PUBLIID + 8))
AUXUSERID=$((USERID - 2))
AUXPUBLIID=$((PUBLIID - 7))
curl --silent -X POST "https://bookspace-app.herokuapp.com/api/comments" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $AUXUSERID, \"content\": \"Me ha parecido una historia genial!!! Espero que tengas mucha suerte el dia de la publicación del libro, manten al foro informado. :)\", \"mentions\": [], \"publicationId\": $AUXPUBLIID}"
AUXPUBLIID=$((PUBLIID - 4))
curl --silent -X POST "https://bookspace-app.herokuapp.com/api/comments" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $AUXUSERID, \"content\": \"Hace poco me he empezado a interesar por el tema!! Te dejo por aquí un link donde se estructura y define muy bien el tema. https://www.santaluciaam.es/blog/ahorro-inversion/que-es-gestion-activa-fondos-inversion\", \"mentions\": [], \"publicationId\": $AUXPUBLIID}"
AUXUSERID=$((USERID - 1))
AUXPUBLIID=$((PUBLIID - 6))
curl --silent -X POST "https://bookspace-app.herokuapp.com/api/comments" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $AUXUSERID, \"content\": \"No es una mala idea aunque te recomiendo tener cuidado y no caer en el típico señor de los anillos, saludos.\", \"mentions\": [], \"publicationId\": $AUXPUBLIID}"
AUXUSERID=$USERID
AUXPUBLIID=$((PUBLIID - 7))
curl --silent -X POST "https://bookspace-app.herokuapp.com/api/comments" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $AUXUSERID, \"content\": \"Te recomiendo el libro: El libro de Ragnarök: saga Vanir. Muy recomendado por el público, no te defraudará.\", \"mentions\": [], \"publicationId\": $AUXPUBLIID}"
curl --silent -X POST "https://bookspace-app.herokuapp.com/api/users" -H "accept: */*" -H "Content-Type: application/json" -d "{ \"dob\": \"1998-06-19\", \"email\": \"adriansito98@hotmail.com\", \"favCategories\": [ \"comic\", \"comedy\",\"economy\" ], \"name\": \"Adrian Perez\", \"password\": \"Hello98@\", \"username\": \"adrisito98\"}"
curl --silent -X PUT "https://bookspace-app.herokuapp.com/api/users/$USERID" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"description\": \"Apasionado de los comics, concretamente de Marvel. Si te gusta DC ni se te ocurra ver mis publicaciones.\" }"
curl --silent -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"war\", \"content\": \"Hay un gran campo de batalla que desean minar con agujeros negros. Han pensado en dos opciones: Colocar pequeños agujeros negros con estabilizadores que se destruyen al entrar en contacto con un objeto, como una nave espacial enemiga. Esto hará que el micro-agujero negro libere toda su energía en una millonésima de segundo, destruyendo la nave en una explosión masiva. Colocando grandes agujeros negros sin nada. Cuando una nave espacial enemiga se acerca al agujero negro, la destruirá y la consumirá. ¿Alguno de estos es factible y, de no ser así, existen soluciones alternativas con respecto a los campos de minas en el espacio?\", \"mentions\": [], \"tags\": [ \"guerra\",\"magia\" ], \"title\": \"¿Campos de minas de agujeros negros?\"}"
USERID=$((USERID + 1))
curl --silent -X POST "https://bookspace-app.herokuapp.com/api/users" -H "accept: */*" -H "Content-Type: application/json" -d "{ \"dob\": \"1964-11-14\", \"email\": \"maria.lopez.gil@hotmail.com\", \"favCategories\": [ \"teen\", \"adult\",\"cops\" ], \"name\": \"Maria Lopez\", \"password\": \"Maria64@\", \"username\": \"marialo64\"}"
curl --silent -X PUT "https://bookspace-app.herokuapp.com/api/users/$USERID" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"description\": \"Me encanta leer y crear obras propias, me considero una creadora de contenido clásico.\" }"
curl --silent -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"SciFi\", \"content\": \"En muchos mundos de ciencia ficción y fantasía, los desiertos están llenos de megafauna gigante que nada a través de dunas de arena suelta. El problema con esta descripción, por supuesto, no es solo el tamaño de dichos nadadores de arena, sino de dónde proviene la energía necesaria para tales gigantes. Si miramos el mundo real, los desiertos no tienen una biomasa sustancial necesaria para que ese organismo sobreviva. Y la razón por la que las ballenas crecen a tales tamaños, además de la flotabilidad del agua, es la cantidad de plancton disponible.\", \"mentions\": [], \"tags\": [ \"vida\",\"naturaleza\" ], \"title\": \"Plancton de arena. ¿Es posible?\"}"
curl --silent -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"terror\", \"content\": \"Supongamos que hay una criatura que ataca las narices humanas, si las fosas nasales son visibles. La gente ha descubierto que está a salvo de este monstruo si usa una máscara. No basta con ponerse la mascarilla sobre la boca; también debe cubrir la nariz. El monstruo es tan aterrador que todas las personas usan máscaras y no permiten que sus narices asomen por la parte superior de la máscara. ¿Cómo sería un monstruo así? ¿Por qué esta criatura va detrás de las narices en particular? ¿Cómo este monstruo ataca la nariz? ¿Por qué las máscaras son un elemento disuasorio eficaz? Solo animales (sin COVID, tuberculosis u otros microorganismos).\", \"mentions\": [], \"tags\": [ \"vida\" ], \"title\": \"¿Cómo sería un monstruo que ataca a las narices humanas?\"}"
curl --silent -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"SciFi\", \"content\": \"Entonces, en una historia que estoy escribiendo (que tiene lugar en la Tierra, dentro de tres o cuatro siglos) los animales se rebelan contra los humanos como una fuerza colectiva. Supongo que son principalmente los animales salvajes los que están causando estragos, causando víctimas y demás. El objetivo principal de los animales es sacar a los humanos de su lugar actual de Ultimate Apex Animal. Me pregunto cómo se las arreglarían los animales para derrocar a los humanos. Clasifico su inteligencia en función de su autoconciencia y capacidad para formar planes de algún tipo. Preferiría que no se usara magia para responder a esto.\", \"mentions\": [], \"tags\": [ \"naturaleza\" ], \"title\": \"¿Cómo pueden los animales rebelarse contra los humanos?\"}"
USERID=$((USERID + 1))
curl --silent -X POST "https://bookspace-app.herokuapp.com/api/users" -H "accept: */*" -H "Content-Type: application/json" -d "{ \"dob\": \"1995-10-05\", \"email\": \"juan.alberto.manzano@hotmail.com\", \"favCategories\": [ \"sport\", \"biography\",\"futurism\" ], \"name\": \"Juan Manzano\", \"password\": \"Apple45@\", \"username\": \"applejohn\"}"
curl --silent -X PUT "https://bookspace-app.herokuapp.com/api/users/$USERID" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"description\": \"A quien no le gusta un buen relato futurista?\" }"
curl --silent -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"futurism\", \"content\": \"Suponiendo que la humanidad continúe construyendo estructuras similares a carreteras para el transporte de personas, mercancías, etc., ¿hay materiales candidatos probables para reemplazar las carreteras de asfalto de hoy en día durante los próximos cientos de años?\", \"mentions\": [], \"tags\": [ \"tecnologia\" ], \"title\": \"¿Carreteras del futuro?\"}"
curl --silent -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"fantasy\", \"content\": \"Los dioses en este entorno son seres extremadamente poderosos pero limitados, que son similares a los humanos en su mente y decisiones. Los dioses son los poderes más altos del mundo, pero se originan de la reproducción de la misma manera que otros organismos. La característica principal que separa a los dioses de otras criaturas es que muchos dioses tienen etiquetas escritas en su cuerpo en varios lugares, que muestran los nombres, títulos o cualidades del dios etiquetado. Los dioses tienen varios niveles de etiquetado y algunos dioses no están etiquetados en absoluto. Cada facción de dioses tiene miembros etiquetados y no etiquetados, y algunos de los dioses más poderosos y sin ley también están etiquetados. Varios dioses tienen etiquetas inexactas. ¿Qué razón podría haber para etiquetar a los dioses?\", \"mentions\": [], \"tags\": [ \"vida\" ], \"title\": \"¿Etiquetar a los dioses?\"}"
curl --silent -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"erotic\", \"content\": \"Quiero alejarme de los tópicos y saber que es lo que realmente podría excitar sexualmente a un hombre. Recordad que no tienen porque ser experiencias propias ;)\", \"mentions\": [], \"tags\": [ \"vida\" ], \"title\": \"¿Qué es lo que más excita a un hombre?\"}"
curl --silent -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"crime\", \"content\": \"Todos en este mundo a partir de los 5 años pueden teletransportarse a cualquier lugar en el que hayan estado antes. Esto comenzó alrededor del 4,000 a. C., donde una estrella verde brillante aterrizó en la tierra y afectó a todos los humanos a poder teletransportarse, pueden teletransportarse con ellos 5 veces su peso y si alguien olvida un lugar donde ha estado, no puede ir allí. La razón por la que los jóvenes no pueden teletransportarse es porque la parte del cerebro no está completamente desarrollada. ¿Cómo serían castigadas las personas que, digamos, asesinaron a alguien? Podría irse a casa o ir a un lugar en el que haya estado antes. Algunos delitos serían más difíciles de cometer, como la violación, el asesinato y el secuestro porque la persona que podría ser la víctima podría irse en un instante, pero los delitos como el robo son más fáciles.\", \"mentions\": [], \"tags\": [ \"vida\" ], \"title\": \"¿Como se castigaria a los criminales en un mundo donde cualquiera puede teletransportarse?\"}"
curl --silent -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"war\", \"content\": \"La guerra se desata entre dos naciones. Ambos tienen básicamente el mismo nivel tecnológico, pero uno no usa armas de mano. Esto se debe a lo común que es la magia elemental y al fuerte desaliento de las clases superiores y guerreras. Todavía tienen tanques y artillería, pero nada lo suficientemente pequeño como para que una sola persona pueda llevarlo a la batalla. El problema con la magia de elementos es su rabia limitada. Tiene un alcance efectivo de 50 a 60 pies (15 a 18 m), pero a ese rango, en realidad, solo toma grandes trozos de tierra, fuego, agua, aire o iluminación y los lanza al enemigo. Para utilizar la magia elemental con total versatilidad y precisión, necesita un rango de 10 a 20 pies (3 a 6 m). En este caso, el bando elemental tiene algunas trincheras y sus exploradores les han informado que tienen un día para prepararse antes de que llegue el otro ejército. ¿Cómo podrían organizar su defensa para negar o al menos mediar en la ventaja de alcance del enemigo?\", \"mentions\": [], \"tags\": [ \"magia\",\"guerra\" ], \"title\": \"¿Cómo se defendería un grupo de magos elementales contra las armas y la artillería de finales de la Primera Guerra Mundial?\"}"
curl --silent -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"SciFi\", \"content\": \"Suponiendo que alrededor del 1% de la población mundial tiene algún tipo de superpoder, alrededor de 70-80 millones de personas en la tierra, y solo el 1% de ellos se han convertido en superhéroes, ¿qué artículos valdría la pena arriesgarse a robar? En una ciudad llena de héroes, ¿qué podría robar un ladrón sin poder que pasaría desapercibido, por así decirlo, o sería lo suficientemente fácil como para ser robado y, sin embargo, el ladrón podría escapar o evitar la persecución, para convertirse en un evento común?\", \"mentions\": [], \"tags\": [ \"magia\",\"superheroes\",\"crimen\" ], \"title\": \"¿En una ciudad llena de superhéroes, ¿qué objetos aún valdría la pena robar?\"}"
USERID=$((USERID + 1))
PUBLIID=$((PUBLIID + 10))
AUXUSERID=$((USERID - 2))
AUXPUBLIID=$((PUBLIID - 3))
curl -X POST "https://bookspace-app.herokuapp.com/api/comments" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $AUXUSERID, \"content\": \"Quizá creando una manera de comunicarse entre especies y creando un reino animal único que evidentemente pasaría por encima de la especie humana\", \"mentions\": [], \"publicationId\": $AUXPUBLIID}"
AUXUSERID=$((USERID - 1))
curl -X POST "https://bookspace-app.herokuapp.com/api/comments" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $AUXUSERID, \"content\": \"Que cada animal de compañía se rebelase contra su familia de dueños sería un buen comienzo, no cabe duda\", \"mentions\": [], \"publicationId\": $AUXPUBLIID}"
AUXPUBLIID=$((PUBLIID - 5))
curl -X POST "https://bookspace-app.herokuapp.com/api/comments" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $AUXUSERID, \"content\": \"Te importaría ser un poco más concreto y limitar los materiales disponibles? Si no las posibilidades son practicamente infinitas...\", \"mentions\": [], \"publicationId\": $AUXPUBLIID}"
AUXUSERID=$USERID
AUXPUBLIID=$((PUBLIID - 2))
curl -X POST "https://bookspace-app.herokuapp.com/api/comments" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $AUXUSERID, \"content\": \"Se me ocurre una terrible criatura que gana tamaño a base de alimentarse de mocos. En un principio puede entrar en cualquier lugar, pero si consigue alojarse en una nariz, podría crecer hasta acabar con su portador desde el interior del mismo. Terrorífico.\", \"mentions\": [], \"publicationId\": $AUXPUBLIID}"
curl -X POST "https://bookspace-app.herokuapp.com/api/users" -H "accept: */*" -H "Content-Type: application/json" -d "{ \"dob\": \"1999-09-15\", \"email\": \"Flytoss8@gmail.com\", \"favCategories\": [ \"romantic\", \"adventure\" ], \"name\": \"Bruno Peralta\", \"password\": \"HJXd5@p9\", \"username\": \"flytoss\"}"
curl -X PUT "https://bookspace-app.herokuapp.com/api/users/$USERID" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"description\": \"No se que poner aquí, mi instagram es @ajsdsajdasj\"}"
curl -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"SciFi\", \"content\": \"Un deformador de la realidad tiene el poder de manipular la realidad. Los usuarios pueden crear, dar forma y manipular la realidad con solo pensar en ella, y pueden alterar algo tan tangible como la física y el universo en algo inconcebible como la lógica. La realidad del reino mortal se mantiene unida por una serie de hilos entrecruzados que están interconectados. Estas cuerdas están atadas a todo lo que vive y no vive dentro del reino, conectando todas las cosas dentro de un reino entre sí, similar a un tapiz. Un warper de la realidad puede ver y manipular mentalmente estas cuerdas para cambiar el mundo que los rodea, alterando lo físico y lo no físico para adaptarse a sus propósitos. Para otros, aparentemente pueden crear cosas de la nada y pueden borrarlas de la existencia con la misma facilidad. Esto prácticamente los convierte en un dios a los ojos de los demás.\", \"tags\": [ \"DeformadorDeRealidad\" ], \"title\": \"¿Cómo puedo explicar los poderes de terraformación de mi deformador de realidad?\"}"
USERID=$((USERID + 1))
curl -X POST "https://bookspace-app.herokuapp.com/api/users" -H "accept: */*" -H "Content-Type: application/json" -d "{ \"dob\": \"2002-03-28\", \"email\": \"Antolvpp4@gmail.com\", \"favCategories\": [ \"teen\", \"sport\" ], \"name\": \"Antonia Gimenez \", \"password\": \"123456AG.\", \"username\": \"Elktfoga\"}"
curl -X PUT "https://bookspace-app.herokuapp.com/api/users/$USERID" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"description\": \"Aquí por los jajas e inspirarme\"}"
curl -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"other\", \"content\": \"Un libro de papel se deteriora considerablemente, incluso si se mantiene en excelentes condiciones: el papel se seca y se vuelve quebradizo, y las tintas pueden decolorarse. ¿Cómo podría esta especie construir un libro, sabiendo que bien puede permanecer en un estante durante decenas de miles de años antes de que sea tocado, y mucho menos leído? ¿Qué materiales podrían usar y aún mantener esa <sensación de libro>?\", \"tags\": [ \"Libro\", \"Eterno\" ], \"title\": \"¿Cómo se puede construir un libro para que dure para siempre?\"}"
curl -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"other\", \"content\": \"Imagínese que viajo en el tiempo 500 años, dejo un libro de registro de barco en una cueva y el libro de registro fue descubierto hoy. Dado que el libro fue descubierto después de que fuera posible comprarlo en el estante, fácilmente podría ser un engaño. Por ejemplo, un libro de registro que se produjo por primera vez en 2015 viajó en el tiempo ~500 años y se encontró en una cueva inexplorada en 2017. ¿Sería posible demostrar de manera concluyente que tiene 500 años y no solo una falsificación convincente? Suponiendo, por supuesto, que alguien realmente se lo haya tomado lo suficientemente en serio como para intentar autenticarlo. Si quisiera que los investigadores / archiveros sospecharan que en realidad tiene ~ 500 años, pero no hay forma de probar que en realidad tiene 500 años, ¿qué tendría que hacer?\", \"tags\": [ \"Libro\", \"tiempo\" ], \"title\": \"¿Se puede demostrar que un libro moderno que viajó en el tiempo es más antiguo?\"}"
curl -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"other\", \"content\": \"Actualmente estoy trabajando en un experimento con Worldbuilding Stack Exchange, por lo que estoy trabajando en un lenguaje construido para que lo utilicen algunas personas de mi mundo. Tengo algunos de los puntos principales abajo, pero también estoy interesado en aprender sobre los aspectos más generales de la construcción del lenguaje. ¿Cuál es un buen libro que habla sobre el proceso de creación de lenguajes construidos? Específicamente, me gustaría uno que se centre en idiomas a posteriori, porque mi idioma se basa en parte en el inglés (británico).\", \"tags\": [ \"Libro\" ], \"title\": \"¿Qué libro es bueno para desarrollar un lenguaje construido a posteriori?\"}"
USERID=$((USERID + 1))
curl -X POST "https://bookspace-app.herokuapp.com/api/users" -H "accept: */*" -H "Content-Type: application/json" -d "{ \"dob\": \"1997-12-30\", \"email\": \"kirkodabest@gmail.com\", \"favCategories\": [ \"sport\" ], \"name\": \"Edin Kirkidaze\", \"password\": \"EKfff87@\", \"username\": \"Kk_87\"}"
curl -X PUT "https://bookspace-app.herokuapp.com/api/users/1" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"description\": \"Apasionado por el mundo de deporte y libros\"}"
curl -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"documentary\", \"content\": \"¿Qué evidencia hay de formas de vida basadas en silicio? Al escribir un libro de ciencia dura, hay mucha 'ciencia' para apoyar tal noción. Ejemplos de otros trabajos serían buenos\", \"tags\": [ \"silicio\" ], \"title\": \"¿Qué evidencia hay de formas de vida basadas en silicio?\"}"
curl -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"sport\", \"content\": \"Volví a leer las novelas de Harry Potter y pensé cuánto Quidditch tiene un sistema de juego roto (los buscadores están muy dominados en comparación con otros jugadores y básicamente pueden llevar a su propio equipo a la victoria independientemente del equipo opuesto. Es porque tienen cerca de no hay mecánicas relacionadas con sus compañeros de equipo, excepto esquivar bludgers y que atrapar la snitch dorada te dan 150 puntos mientras que la mayoría de los juegos tienen menos de 150 puntos de diferencia). Sin embargo, una cosa muy realista sobre el Quidditch es que los magos pueden jugarlo en su jardín y, como tal, sería un buen pasatiempo para los magos jóvenes, de la misma manera que se puede jugar al fútbol en la calle o en tu jardín. Recordé que todos los deportes sobre los que leí en los libros de ciencia ficción tenían defectos de una forma u otra. Lo importante a considerar para diseñar un deporte realista (y popular) no es lo divertido que es jugarlo, sino también lo divertido que es verlo jugar, por ejemplo, el tenis es divertido de jugar y mirar, jugar al squash. es más divertido de jugar (en mi opinión) pero es extremadamente difícil de ver. Entiendo que la mayoría de los deportes de ficción están ahí por su valor narrativo, pero supongo que podríamos hacerlo mejor. Entonces, aquí están mis preguntas, tenga en cuenta que no estoy buscando ideas para deportes de ficción: ¿Cómo puedo crear deportes bien diseñados? ¿Cuáles son las buenas reglas generales? ¿Cuáles son algunos ejemplos de deportes de equipo ficticios que son realistas? ¿Cuáles son los errores que se cometen comúnmente?\", \"tags\": [ \"sport\" ], \"title\": \"¿Cómo creo un deporte de equipo popular y ficticio?\"}"
curl -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"sport\", \"content\": \" Estoy escribiendo un libro sobre deportes y allí mi duda, ¿Qué deportes olímpicos tienen mecánicas que tienden inherentemente a anular ventajas o desventajas en fuerza, altura, tamaño o dureza?\", \"tags\": [ \"sport\", \"alien\" ], \"title\": \"¿Qué deportes olímpicos dejarían encajar a los extraterrestres eliminando las ventajas de tamaño, fuerza, etc.?\"}"
curl -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"sport\", \"content\": \" Estoy escribiendo un libro sobre deportes olímpicos donde compite en juego extraterrestres con humanos, decidme que opinais, gracias por adelanto.\", \"tags\": [ \"sport\", \"alien\" ], \"title\": \"¿Os parecería interesante este temario? Necesito consejos y opiniones por favor\"}"
curl -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"sport\", \"content\": \" Estoy escribiendo un libro sobre deportes olímpicos donde compite en juego extraterrestres con humanos, decidme que opinais, gracias por adelanto. No voy a adelantar mucho el spoiler pero se basará en como luchan los humanos con los aliens en un juego equilibrado donde las normas no favorecerá ninguna especie y tal\", \"tags\": [ \"sport\", \"alien\" ], \"title\": \"Última pregunta, comprariais o leerías mi libro? Like si te gusta y dislike si no te interesa\"}"
curl -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"sport\", \"content\": \" Muchisimas gracias! El link para mi libro es https://www.audible.es/?source_code=GGLTM1220926200001&ipRedirectOverride=true&overrideBaseCountry=true&gclid=CjwKCAjwqcKFBhAhEiwAfEr7zZaA3LIrhd5hdvMz6quPfx0Ephg64VV18BJBJo88rxd9i07Q0p064xoCYO8QAvD_BwE&gclsrc=aw.ds\", \"tags\": [ \"sport\", \"alien\" ], \"title\": \"Ya publiqué mi libro, lo podéis encontrar en Amazon books, dejadme opiniones!\"}"
USERID=$((USERID + 1))
PUBLIID=$((PUBLIID + 10))
AUXUSERID=$((USERID - 2))
AUXPUBLIID=$((PUBLIID - 3))
curl -X POST "https://bookspace-app.herokuapp.com/api/comments" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $AUXUSERID, \"content\": \"@willy mira esto\", \"mentions\": [ \"willy\" ], \"parentId\": 0, \"publicationId\": $AUXPUBLIID}"
AUXUSERID=$((USERID - 1))
curl -X POST "https://bookspace-app.herokuapp.com/api/comments" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $AUXUSERID, \"content\": \"Me parece interesantisimo, sigue adelante, espero que lo publiques pronto!\", \"mentions\": [ ], \"parentId\": 0, \"publicationId\": $AUXPUBLIID}"
AUXUSERID=$((USERID - 6))
curl -X POST "https://bookspace-app.herokuapp.com/api/comments" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $AUXUSERID, \"content\": \"Hay un deporte aparentemente oscuro llamado curling que requiere estrategia y refinamiento de movimientos finos en lugar de potencia bruta. Efectivamente, el lento movimiento Cephalapori encajó muy bien, capaz y lo suficientemente rápido (en hielo) para lanzar piedras y barrer, aunque solo una escoba. Son los favoritos de los medios, lucen sus gorras de Detroit Redwings y llaman <yeongmi> (nadie les ha dicho que solo digas <escoba>), y ganan aproximadamente la mitad de los juegos, excepto contra las naciones nórdicas o Corea. El Cheetara saltó sobre él también una vez que se dieron cuenta de que nadie se quejaría de ellos. El juego pone todas las carreras a la par. Entonces hay un ejemplo de un deporte que funciona.\", \"mentions\": [ \"Kk_87\", \"flytoss\" ], \"parentId\": 0, \"publicationId\": $AUXPUBLIID}"
AUXUSERID=$USERID
curl -X POST "https://bookspace-app.herokuapp.com/api/comments" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $AUXUSERID, \"content\": \"Gracias por vuestra ayuda!\", \"mentions\": [ \"Kk_87\", \"flytoss\" ], \"parentId\": 0, \"publicationId\": $AUXPUBLIID}"
curl -X POST "https://bookspace-app.herokuapp.com/api/users" -H "accept: */*" -H "Content-Type: application/json" -d "{ \"dob\": \"1986-06-16\", \"email\": \"ESJorgeSan@gmail.com\", \"favCategories\": [ \"futurism\", \"SciFi\",\"action\",\"fantasy\" ], \"name\": \"Jorge Sanchez\", \"password\": \"Bookspace123@\", \"username\": \"obi.kenobi\"}"
curl -X PUT "https://bookspace-app.herokuapp.com/api/users/$USERID" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"description\": \"<<El miedo es el camino hacia el Lado Oscuro. El miedo lleva a la ira, la ira lleva al odio, el odio lleva al sufrimiento. Percibo mucho miedo en ti>>, Maestro Yoda..\" }"
USERID=$((USERID + 1))
curl -X POST "https://bookspace-app.herokuapp.com/api/users" -H "accept: */*" -H "Content-Type: application/json" -d "{ \"dob\": \"2000-11-29\", \"email\": \"20lildrago00@gmail.com\", \"favCategories\": [ \"teen\", \"comedy\", \"comic\" ], \"name\": \"Aurora Ortega\", \"password\": \"Bookspace123@\", \"username\": \"TheLiLDrago_\"}"
curl -X PUT "https://bookspace-app.herokuapp.com/api/users/$USERID" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"description\": \"Soy una book enjoyer a la que le encanta plasmar su creatividad mediante la narración de historias. Vengo a aprender y contribuir en esta maravillosa comunidad :D\" }"
USERID=$((USERID + 1))
curl -X POST "https://bookspace-app.herokuapp.com/api/users" -H "accept: */*" -H "Content-Type: application/json" -d "{ \"dob\": \"1964-02-12\", \"email\": \"a.fernandez.del.real@outlook.com\", \"favCategories\": [ \"literary\", \"historic\", \"poetry\", \"theater\", \"documentary\" ], \"name\": \"Alejandro Fernández\", \"password\": \"Bookspace123@\", \"username\": \"alejandrodelreal\"}"
curl -X PUT "https://bookspace-app.herokuapp.com/api/users/$USERID" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"description\": \"Mi nombre es Alejandro, soy licenciado en literatura y filosofía clásica. Regento una hemeroteca en Sevilla y en mis tiempos libres me encanta declamar obras en compañía de mis amigos.\" }"
USERID=$((USERID + 1))
curl -X POST "https://bookspace-app.herokuapp.com/api/users" -H "accept: */*" -H "Content-Type: application/json" -d "{ \"dob\": \"1998-06-19\", \"email\": \"PalomaMami@hotmail.com\", \"favCategories\": [ \"comedy\",\"economy\" ], \"name\": \"Paloma Álvarez\", \"password\": \"Contra123@\", \"username\": \"Palomita\"}"
curl -X PUT "https://bookspace-app.herokuapp.com/api/users/$USERID" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"description\": \"Soy lectora desde pequeña, los mejores recuerdos que tengo son de mi padre leyendo antes de dormir.\" }"
curl -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"history\", \"content\": \"En mi serie de libros, la magia es una habilidad que se puede aprender y que cualquier persona puede aprender hasta cierto punto (aunque algunos tienen mucho más talento natural que otros y dominar incluso una sola disciplina de la magia requiere años de entrenamiento y experiencia). Sin embargo, en mi serie de libros, la magia (fuera del elenco principal de personajes) solo es utilizada por varios sacerdotes para rituales religiosos y por navegantes (que imbuyen Magia Astral en estos cristales especiales que cuando se unen a los barcos, los encantan en los Lectores de Inicio FTL Esbocé en una pregunta diferente mía). ¿Cómo podría justificar la restricción de la magia de esta manera si alguien técnicamente puede aprenderla?\", \"mentions\": [], \"tags\": [], \"title\": \"¿Cómo justificaría mantener la mayor parte de la magia alejada del público en general si todos pueden aprenderla técnicamente?\"}"
USERID=$((USERID + 1))
curl -X POST "https://bookspace-app.herokuapp.com/api/users" -H "accept: */*" -H "Content-Type: application/json" -d "{ \"dob\": \"2000-01-13\", \"email\": \"tRexMeteor@hotmail.com\", \"favCategories\": [  \"comic\", \"teen\", \"adult\" ], \"name\": \"Rex Smith\", \"password\": \"Contra123@\", \"username\": \"Rex123\"}"
curl -X PUT "https://bookspace-app.herokuapp.com/api/users/$USERID" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"description\": \"Los géneros adolescentes siempre han sido mis preferidos, quiero encontrar nuevos gustos.\" }"
curl -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"SciFi\", \"content\": \"Una de las mecánicas del escenario que estoy desarrollando incluye armas de alma. Uno de sus principales aspectos es que pueden volverse etéreos y atravesar la materia. Entonces, ¿qué pasaría si alguien golpeara una pared o una persona mientras es etérea y la volviera sólida dentro de ellos? Supongamos que ese arma, una espada como ejemplo, se materializa de adentro hacia afuera sin superponerse con otros átomos ni ocupar repentinamente el mismo espacio que ellos. Suponga también que para todos los efectos, cuando se materializa, el arma está hecha de átomos reales y que no importa cuán fuerte sea el material, el arma siempre se materializará por completo.\", \"mentions\": [], \"tags\": [\"naturaleza\" ], \"title\": \" ¿Qué pasaría si un arma se materializara dentro de un objeto?\"}"
curl -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"terror\", \"content\": \"Imaginad una historia donde todos los personajes tienen la piel invertida, donde las personas que dan miedo son las que tienen aspecto de humanos actuales. Creeis que habria racismo? De que tipo? \", \"mentions\": [], \"tags\": [ \"vida\", \"zombies\" ], \"title\": \"Estamos en una sociedad racista por naturaleza?\"}"
curl -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"kitchen\", \"content\": \"Recomendación de libros de cocina para aprender a cocinar, los huevos fritos se me resisten y no se hacer nada.\", \"mentions\": [], \"tags\": [ \"naturaleza\" ], \"title\": \"¿Cómo pueden los animales rebelarse contra los humanos?\"}"
USERID=$((USERID + 1))
curl -X POST "https://bookspace-app.herokuapp.com/api/users" -H "accept: */*" -H "Content-Type: application/json" -d "{ \"dob\": \"1995-12-25\", \"email\": \"SugarDaddy@hotmail.com\", \"favCategories\": [ \"biography\",\"futurism\", \"cops\"], \"name\": \"Rhino Dino\", \"password\": \"Contra123@\", \"username\": \"RhinoDino\"}"
curl -X PUT "https://bookspace-app.herokuapp.com/api/users/$USERID" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"description\": \"Rwaaaaaaarrrr, he sobrevivido al meteorito\"}"
USERID=$((USERID + 1))
PUBLIID=$((PUBLIID + 4))
curl -X POST "https://bookspace-app.herokuapp.com/api/users" -H "accept: */*" -H "Content-Type: application/json" -d "{ \"dob\": \"1992-01-20\", \"email\": \"maax92@hotmail.com\", \"favCategories\": [ \"contemporary\", \"poetry\",\"economy\",\"war\" ], \"name\": \"Max Katz\", \"password\": \"Bookspace123@\", \"username\": \"maax92\"}"
curl -X PUT "https://bookspace-app.herokuapp.com/api/users/$USERID" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"description\": \"Qué maravilloso es que nadie necesite esperar ni un sólo momento antes de comenzar a mejorar el mundo.\" }"
curl -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"fantasy\", \"content\": \"Tengo un grupo de magos del tiempo (que solo usan magia del tiempo) que están atacando un país que acaba de experimentar una revolución industrial mágica masiva. Estos magos son terroristas y tienen un hechizo que puede rebobinar 100 kg de plomo en una pieza de uranio con masa equivalente. El hechizo puede alcanzar los 30 pies y tiene encantamientos y movimientos de brazos obvios, pero la magia es común, por lo que la mayoría de la gente no lo piensa dos veces. ¿Cómo usan este hechizo para causar tanto pánico como sea posible en esta sociedad?\", \"mentions\": [], \"tags\": [ \"revolución\",\"magia\" ], \"title\": \"¿Cómo es que un grupo de magos terroristas que puede convertir el plomo en uranio causa el mayor daño en una sociedad de revolución industrial?\"}"
USERID=$((USERID + 1))
curl -X POST "https://bookspace-app.herokuapp.com/api/users" -H "accept: */*" -H "Content-Type: application/json" -d "{ \"dob\": \"1967-06-19\", \"email\": \"avillarreal@protonmail.com\", \"favCategories\": [ \"suspense\",\"erotic\",\"drama\",\"futurism\" ], \"name\": \"Alessio Villarreal\", \"password\": \"Bookspace123@\", \"username\": \"alessio_villarreal\"}"
curl -X PUT "https://bookspace-app.herokuapp.com/api/users/$USERID" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"description\": \"No todos aquellos que viajan sin rumbo están perdidos. Me encantan las novelas de suspense futurísticas con elementos paranormales.\" }"
curl -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"SciFi\", \"content\": \"Estoy tratando de hacer un universo usando matemáticas y este es un planeta del primer sistema solar que estoy creando. Primero la estrella. Esta estrella, para la que no tengo un nombre, tiene una masa de 1,3 masas solares, una luminosidad de 2,19 veces la de nuestro sol, un diámetro de 3049964,86 km (1895160,3 millas), una temperatura superficial. de 6596 K, o 1,14 veces la de nuestro sol. La zona habitable se encuentra entre 1,4 AU y 2,02 AU. La línea de congelación está en 7.17 AU y los límites internos y externos del sistema están ubicados en 0.13 AU y 52 AU. Ahora el planeta. Este planeta, una vez más aún no me he hecho con un nombre, tiene una masa de 2,8 masas terrestres, un radio de 9556,6 km (5938,2 millas), un semieje mayor de 1,72 UA, una gravedad superficial de 13,3 m / s^2, una excentricidad de 0,1 y una inclinación axial de 25,4 grados. PD. Solicita más detalles si los necesitas porque no puedo pensar en ningún otro detalle que tenga que agregar.\", \"mentions\": [], \"tags\": [ \"universo\",\"planetas\" ], \"title\": \"¿Este planeta sería habitable para formas de vida inteligentes? Necesito una opinión objetiva\"}"
curl -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"futurism\", \"content\": \"Todos hemos oído hablar del motor de diferencia Babbage de 1822 y otras ideas de computadoras mecánicas del siglo XIX. Lamentablemente, las ideas sobre computadoras e impresoras de Babbage nunca se implementaron en nuestro mundo, y las computadoras no existieron hasta la década de 1940. Ahora imagine un mundo donde esto se logró, como lo fue en poco tiempo su Motor Analítico más elaborado, y las revoluciones industrial y mecano-informática fueron de la mano. Según la ley de cálculo de Lovelace (1843), la cantidad de columnas de cálculo por libra troy de maquinaria de acero se duplica cada 5 años. Ahora es importante señalar que el motor analítico (en el diseño teórico de la máquina de Babbage, así como en la práctica diaria de nuestro mundo alternativo) era lo que en nuestro mundo hemos llegado a llamar Turing completo, es decir, es una computadora universal. Digital, totalmente programable. Dejando de lado las implicaciones que cambiaron el mundo de tal advenimiento, tengo curiosidad por pensar en los límites de la 'Ley de Lovelace': cuán miniaturizada y cuán poderosa podría ser concebiblemente una computadora mecánica, antes de que se requiriera una revolución kuhniana. ¿Cómo pasar a dispositivos electromecánicos? No partimos de un listón alto. Como referencia inicial, el diseño inicial del motor analítico tenía el equivalente a una memoria de 16,7 kB, y el molino de procesamiento central podía manejar una multiplicación de dos números de 20 dígitos en aproximadamente 3 minutos. El primer aritmómetro de Thomas de Colmar no era una computadora de propósito general, pero podía multiplicar dos números de ocho dígitos en 18 segundos. ¿Seríamos capaces de alcanzar, digamos, los niveles informáticos de la era de 1950?\", \"mentions\": [], \"tags\": [ \"ordenador\",\"evolución\",\"tecnología\" ], \"title\": \"¿Qué tan poderoso podría ser un ordenador mecánico? ¿Podría llegar a la potencia de un ordenador de los años 50?\"}"
curl -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"SciFi\", \"content\": \"¿Cómo se calculan las necesidades calóricas de varias criaturas considerando sus diferentes comportamientos, latidos cardíacos ... hormonas, tipos de sangre, habilidades, temperatura corporal, temperatura externa, gravedad  y densidad del aire? Estoy buscando una fórmula única que tenga en cuenta todos estos factores a la vez.\", \"mentions\": [], \"tags\": [ \"criaturas\",\"biología\" ], \"title\": \"¿Cómo calcular las calorías necesarias para mis seres y criaturas inventadas de mi historia?\"}"
USERID=$((USERID + 1))
curl -X POST "https://bookspace-app.herokuapp.com/api/users" -H "accept: */*" -H "Content-Type: application/json" -d "{ \"dob\": \"1988-02-04\", \"email\": \"rilay@dramax.es\", \"favCategories\": [ \"action\",\"adventure\",\"comedy\" ], \"name\": \"Maria Rilay\", \"password\": \"Bookspace123@\", \"username\": \"mrilay\"}"
curl -X PUT "https://bookspace-app.herokuapp.com/api/users/$USERID" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"description\": \"Escribir para mí no es una profesión, ni siquiera una vocación. Es una manera de estar en el mundo, de ser, no se puede hacer otra cosa. Se es escritor. Bueno o malo, ya es otra cuestión.\" }"
curl -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"SciFi\", \"content\": \"Necesito una forma de hacer posible la vida en la troposfera y la estratosfera inferior para mi escenario ambientado en un futuro lejano. Mi excusa para trasladar la vida a estas altitudes es aumentar los niveles de oxígeno en la atmósfera, por lo que vivir al nivel del mar es tóxico, y la razón del aumento de los niveles de oxígeno es algún tipo de gran evento de oxidación con un nuevo tipo de cianobacteria. Tal como está, la temperatura de la troposfera va de -60 °C por la tropopausa a alrededor de 0 ° cuando llegamos a la estratosfera superior y la capa de ozono. ¿Cambiaría esto de alguna manera significativa si los niveles de oxígeno se duplicaran, triplicaran o cuadruplicaran? ¿Podría la vida de otra manera incapaz de inhibir estas zonas de repente tener acceso a ellas?\", \"mentions\": [], \"tags\": [ \"atmósfera\" ], \"title\":  \"¿Cambiarían las temperaturas en la troposfera y la estratosfera si los niveles de oxígeno aumentaran significativamente?\"}"
curl -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"SciFi\", \"content\": \"La persona a sacrificar puede ser parte de un ritual con o sin consentimiento, pero plantea menos problemas morales si la persona consiente en el sacrificio. Para muchas sociedades antes de la edad clásica, el ritual del sacrificio humano era una práctica común. La costumbre cesó antes de la Edad Media principalmente por motivos religiosos. Pero, ¿es posible que una sociedad mantenga esas prácticas aceptables durante la Edad Media y más allá (con o sin el consentimiento de la víctima)?\", \"mentions\": [], \"tags\": [ \"sociedad\",\"cultura\" ], \"title\": \"¿Es posible que una sociedad desarrollada practique el sacrificio humano como ritual?\"}"
curl -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"SciFi\", \"content\": \"Estoy teniendo a Gorgonas (como Medusa) como protagonistas en el escenario de mi historia. No son exclusivamente mujeres, tienen la parte inferior del cuerpo de una serpiente y el elemento clásico de serpientes por cabello que tenían las gorgonas en la mitología griega. Sin embargo, no estoy segura de cómo las serpientes que forman su cabello se adherirían realmente a sus cráneos. Sé que las serpientes tienen sus propios corazones y pulmones pero no tienen órganos digestivos, que tienen sus propios cerebros que les permiten actuar de forma autónoma hasta cierto punto, pero que las Gorgonas también pueden controlarlas conscientemente cuando quieran, al menos en la mayoría de los casos. parte. Pero es la parte de la conexión la que me está dando problemas. ¿Cómo se adhiere la columna vertebral de una serpiente a un cráneo humanoide?\", \"mentions\": [], \"tags\": [ \"biología\",\"mitología\",\"anatomía\" ], \"title\": \"¿Cómo se conectan las serpientes en la cabeza de las Gorgonas con el cráneo?\"}"
curl -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"fantasy\", \"content\": \"Me encuentro en esta situación: Mis personajes están en una tierra compuesta principalmente por ciudades estado con cierto grado de reconocimiento de nacionalidad común (a la griega en la época de las guerras persas), la tierra ha sido conquistada por el imperio que es su vecino del norte, a excepción de una de las ciudades más grandes, que está sitiada. Formaron una pequeña fuerza de rebelión (un cliché, lo sé) y obtuvieron una victoria afortunada, ahora un ejército imperial ha entrado en la tierra y está a unos días de marcha de su fuerza mucho más pequeña, sin entrenamiento y menos equipada. La tierra tiene muchos bosques densos y campos ricos para que se escondan y coman, así como algunas cadenas montañosas grandes. La población debería estar en su mayor parte del lado de los rebeldes. Me está costando descifrar varias cosas. Me doy cuenta de que deberían emplear alguna forma de guerra de guerrillas, pero no entiendo cómo un ejército que no está entrenado, no está equipado y no tiene suministro confiable de alimentos o agua puede hacerlo, contra una fuerza que es todas estas cosas. Espero que esta pregunta esté bien, gracias de antemano.\", \"mentions\": [], \"tags\": [ \"revolución\",\"medioevo\" ], \"title\": \"Mundo de fantasía medieval, fuerzas rebeldes contra un imperio, ¿cómo pueden ganar los rebeldes?\"}"
curl -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"SciFi\", \"content\": \"El mundo que estoy construyendo, Qi'raad, orbita un agujero negro de masa estelar. ¿Cómo se adaptaría mejor la vida para sobrevivir? Además, el agujero negro, llamado Halku, emite un chorro de radio relativamente delgado, que ha excavado un gran cañón en la eclíptica de Qi'raad. El planeta aún no está bloqueado por las mareas.\", \"mentions\": [], \"tags\": [ \"universo\",\"planetas\",\"agujero negro\" ], \"title\": \"¿Cómo se adaptaría la vida inteligente en un planeta con agujeros negros?\"}"
curl -X POST "https://bookspace-app.herokuapp.com/api/publications" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $USERID, \"category\": \"SciFi\", \"content\": \"La sociedad en cuestión estaría compuesta por una sola especie no humana que evolucionó naturalmente. Están dirigidos por un rey, junto con varios duques que administran porciones más pequeñas del reino. Para distinguir a estos líderes del resto de la población, son mucho más grandes, los duques son dos veces más grandes y los reyes son tres veces más grandes. También tienen otras características, como armas y ornamentos naturales más pronunciados. Sin embargo, hay una arruga en este sistema: los reyes y duques son elegidos por la población. ¿Qué características podría tener esta especie, que podría ser cooptada por la sociedad para hacer a los reyes y duques tan impresionantes?\", \"mentions\": [], \"tags\": [ \"sociedad\" ], \"title\": \"¿Cómo podría un funcionario electo hacerse anatómicamente diferente del resto de la sociedad?\"}"
USERID=$((USERID + 1))
PUBLIID=$((PUBLIID + 10))
ENDUSER=$USERID
ENDRANGE=$PUBLIID
AUXUSERID=$((USERID - 2))
AUXPUBLIID=$((PUBLIID - 3))
curl -X POST "https://bookspace-app.herokuapp.com/api/comments" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $AUXUSERID, \"content\": \"Cualquier elemento tiene isótopos inestables que son radiactivos. Eso podría ser lo que deseas considerar además de cambiar el elemento o en lugar de hacerlo. El uranio tiene una vida media larga, lo que significa que es relativamente menos radiactivo que otros elementos radiactivos. Los elementos más radioactivos, aquellos con vidas medias más cortas, son el radio y el radón, que resultan de la desintegración del uranio. Entonces, para tu historia, podrías considerar convertir el plomo en radio o gas radón, lo que sería mucho más mortal.\", \"mentions\": [], \"publicationId\": $AUXPUBLIID}"
AUXUSERID=$((USERID - 1))
curl -X POST "https://bookspace-app.herokuapp.com/api/comments" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $AUXUSERID, \"content\": \"Sí, por ejemplo, si una sociedad estuviera tan avanzada desde el punto de vista médico que sus miembros fueran efectivamente inmortales, podría desarrollar una tradición / requisito legal de que para tener hijos, tendría que encontrar a alguien que se ofreciera voluntariamente como sacrificio humano. Esta tradición / requisito legal podría fácilmente desarrollar elementos rituales a lo largo del tiempo. Básicamente, se necesita una creencia generalizada de que sucederá algo terrible si se detienen los sacrificios. P.ej. los aztecas creían que detenerse causaría el apocalipsis, los habitantes de la bóveda en el ejemplo de lluvia radiactiva anterior creían que la tecnología de la bóveda los mataría si paraban, el ejemplo hipotético que la sociedad creería que detenerse conduciría a un crecimiento demográfico insostenible.\", \"mentions\": [], \"publicationId\": $AUXPUBLIID}"
AUXUSERID=$((USERID - 6))
curl -X POST "https://bookspace-app.herokuapp.com/api/comments" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $AUXUSERID, \"content\": \"Piensa en los tentáculos de un pulpo y cómo están conectados a la cabeza. Sin huesos, pero son móviles y bastante autónomos. Lo mismo ocurre con los pelos de serpiente de tu gorgona: el cráneo está cubierto con un tejido parecido a un molusco del que parten los tentáculos / serpientes / cabello.\", \"mentions\": [], \"publicationId\": $AUXPUBLIID}"
AUXUSERID=$USERID
curl -X POST "https://bookspace-app.herokuapp.com/api/comments" -H "accept: */*" -H "auth: AUTH" -H "Content-Type: application/json" -d "{ \"authorId\": $AUXUSERID, \"content\": \"Cráneos con agujeros. Así de simple.\", \"mentions\": [], \"publicationId\": $AUXPUBLIID}"
for n in `seq 1 100`; do 
RANDUSER=$(( $((RANDOM * ($ENDUSER-$INIUSER+1) / 32768 + INIUSER)) ))
RANDPUBLI=$(( $((RANDOM * ($ENDRANGE-$INIRANGE+1) / 32768 + INIRANGE)) ))
curl -X POST "https://bookspace-app.herokuapp.com/api/publications/$RANDPUBLI/like/$RANDUSER" -H "accept: */*" -H "auth: AUTH"
done
for n in `seq 1 50`; do 
RANDUSER=$(( $((RANDOM * ($ENDUSER-$INIUSER+1) / 32768 + INIUSER)) ))
RANDPUBLI=$(( $((RANDOM * ($ENDRANGE-$INIRANGE+1) / 32768 + INIRANGE)) ))
curl -X POST "https://bookspace-app.herokuapp.com/api/publications/$RANDPUBLI/dislike/$RANDUSER" -H "accept: */*" -H "auth: AUTH"
done